name: al_medynah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  intl: ^0.20.2
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  dio: ^5.9.2
  shared_preferences: ^2.5.5
  http: ^1.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_tts: ^4.2.5
  muslim_data_flutter: ^1.5.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  adhan: ^2.0.0+1
  sensors_plus: ^6.1.1
  video_player: ^2.11.1
  chewie: ^1.13.1
  archive: ^4.0.2
  share_plus: ^10.1.4
  hijri: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app icon 2.png"
  adaptive_icon_background: "#3E2A0F"
  adaptive_icon_foreground: "assets/images/app icon 2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - packages/muslim_data_flutter/assets/db/muslim_db_v2.7.0.db
    - assets/images/background2.png
    - assets/images/logo.jpg
    - assets/images/surah_header_frames.png
    - assets/images/tafseer.png
    - assets/images/tasbih.png
    - assets/images/azkar.png
    - assets/images/tv.png
    - assets/images/Allah_names.png
    - assets/images/hadyth.png
    - assets/images/qublah.png
    - assets/images/reciters.png
    - assets/images/prayertime.png
    - assets/quran_data/verses.json

