class SurahModel {
  final int id;
  final String nameArabic;
  final String nameEnglish;
  final int versesCount;
  final int pageNumber;
  final String revelationType;

  const SurahModel({
    required this.id,
    required this.nameArabic,
    required this.nameEnglish,
    required this.versesCount,
    required this.pageNumber,
    required this.revelationType,
  });
}

const List<SurahModel> surahList = [
  SurahModel(
    id: 1,
    nameArabic: 'الفاتحة',
    nameEnglish: 'Al-Fatihah',
    versesCount: 7,
    pageNumber: 1,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 2,
    nameArabic: 'البقرة',
    nameEnglish: 'Al-Baqarah',
    versesCount: 286,
    pageNumber: 2,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 3,
    nameArabic: 'آل عمران',
    nameEnglish: 'Ali \'Imran',
    versesCount: 200,
    pageNumber: 50,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 4,
    nameArabic: 'النساء',
    nameEnglish: 'An-Nisa',
    versesCount: 176,
    pageNumber: 77,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 5,
    nameArabic: 'المائدة',
    nameEnglish: 'Al-Ma\'idah',
    versesCount: 120,
    pageNumber: 106,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 6,
    nameArabic: 'الأنعام',
    nameEnglish: 'Al-An\'am',
    versesCount: 165,
    pageNumber: 128,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 7,
    nameArabic: 'الأعراف',
    nameEnglish: 'Al-A\'raf',
    versesCount: 206,
    pageNumber: 151,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 8,
    nameArabic: 'الأنفال',
    nameEnglish: 'Al-Anfal',
    versesCount: 75,
    pageNumber: 177,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 9,
    nameArabic: 'التوبة',
    nameEnglish: 'At-Tawbah',
    versesCount: 129,
    pageNumber: 187,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 10,
    nameArabic: 'يونس',
    nameEnglish: 'Yunus',
    versesCount: 109,
    pageNumber: 208,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 11,
    nameArabic: 'هود',
    nameEnglish: 'Hud',
    versesCount: 123,
    pageNumber: 221,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 12,
    nameArabic: 'يوسف',
    nameEnglish: 'Yusuf',
    versesCount: 111,
    pageNumber: 235,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 13,
    nameArabic: 'الرعد',
    nameEnglish: 'Ar-Ra\'d',
    versesCount: 43,
    pageNumber: 249,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 14,
    nameArabic: 'إبراهيم',
    nameEnglish: 'Ibrahim',
    versesCount: 52,
    pageNumber: 255,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 15,
    nameArabic: 'الحجر',
    nameEnglish: 'Al-Hijr',
    versesCount: 99,
    pageNumber: 262,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 16,
    nameArabic: 'النحل',
    nameEnglish: 'An-Nahl',
    versesCount: 128,
    pageNumber: 267,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 17,
    nameArabic: 'الإسراء',
    nameEnglish: 'Al-Isra',
    versesCount: 111,
    pageNumber: 282,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 18,
    nameArabic: 'الكهف',
    nameEnglish: 'Al-Kahf',
    versesCount: 110,
    pageNumber: 293,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 19,
    nameArabic: 'مريم',
    nameEnglish: 'Maryam',
    versesCount: 98,
    pageNumber: 305,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 20,
    nameArabic: 'طه',
    nameEnglish: 'Ta-Ha',
    versesCount: 135,
    pageNumber: 312,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 21,
    nameArabic: 'الأنبياء',
    nameEnglish: 'Al-Anbiya',
    versesCount: 112,
    pageNumber: 322,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 22,
    nameArabic: 'الحج',
    nameEnglish: 'Al-Hajj',
    versesCount: 78,
    pageNumber: 332,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 23,
    nameArabic: 'المؤمنون',
    nameEnglish: 'Al-Mu\'minun',
    versesCount: 118,
    pageNumber: 342,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 24,
    nameArabic: 'النور',
    nameEnglish: 'An-Nur',
    versesCount: 64,
    pageNumber: 350,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 25,
    nameArabic: 'الفرقان',
    nameEnglish: 'Al-Furqan',
    versesCount: 77,
    pageNumber: 359,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 26,
    nameArabic: 'الشعراء',
    nameEnglish: 'Ash-Shu\'ara',
    versesCount: 227,
    pageNumber: 367,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 27,
    nameArabic: 'النمل',
    nameEnglish: 'An-Naml',
    versesCount: 93,
    pageNumber: 377,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 28,
    nameArabic: 'القصص',
    nameEnglish: 'Al-Qasas',
    versesCount: 88,
    pageNumber: 385,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 29,
    nameArabic: 'العنكبوت',
    nameEnglish: 'Al-\'Ankabut',
    versesCount: 69,
    pageNumber: 396,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 30,
    nameArabic: 'الروم',
    nameEnglish: 'Ar-Rum',
    versesCount: 60,
    pageNumber: 404,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 31,
    nameArabic: 'لقمان',
    nameEnglish: 'Luqman',
    versesCount: 34,
    pageNumber: 411,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 32,
    nameArabic: 'السجدة',
    nameEnglish: 'As-Sajdah',
    versesCount: 30,
    pageNumber: 415,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 33,
    nameArabic: 'الأحزاب',
    nameEnglish: 'Al-Ahzab',
    versesCount: 73,
    pageNumber: 418,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 34,
    nameArabic: 'سبأ',
    nameEnglish: 'Saba',
    versesCount: 54,
    pageNumber: 428,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 35,
    nameArabic: 'فاطر',
    nameEnglish: 'Fatir',
    versesCount: 45,
    pageNumber: 434,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 36,
    nameArabic: 'يس',
    nameEnglish: 'Ya-Sin',
    versesCount: 83,
    pageNumber: 440,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 37,
    nameArabic: 'الصافات',
    nameEnglish: 'As-Saffat',
    versesCount: 182,
    pageNumber: 446,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 38,
    nameArabic: 'ص',
    nameEnglish: 'Sad',
    versesCount: 88,
    pageNumber: 453,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 39,
    nameArabic: 'الزمر',
    nameEnglish: 'Az-Zumar',
    versesCount: 75,
    pageNumber: 458,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 40,
    nameArabic: 'غافر',
    nameEnglish: 'Ghafir',
    versesCount: 85,
    pageNumber: 467,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 41,
    nameArabic: 'فصلت',
    nameEnglish: 'Fussilat',
    versesCount: 54,
    pageNumber: 477,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 42,
    nameArabic: 'الشورى',
    nameEnglish: 'Ash-Shuraa',
    versesCount: 53,
    pageNumber: 483,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 43,
    nameArabic: 'الزخرف',
    nameEnglish: 'Az-Zukhruf',
    versesCount: 89,
    pageNumber: 489,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 44,
    nameArabic: 'الدخان',
    nameEnglish: 'Ad-Dukhan',
    versesCount: 59,
    pageNumber: 496,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 45,
    nameArabic: 'الجاثية',
    nameEnglish: 'Al-Jathiyah',
    versesCount: 37,
    pageNumber: 499,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 46,
    nameArabic: 'الأحقاف',
    nameEnglish: 'Al-Ahqaf',
    versesCount: 35,
    pageNumber: 502,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 47,
    nameArabic: 'محمد',
    nameEnglish: 'Muhammad',
    versesCount: 38,
    pageNumber: 507,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 48,
    nameArabic: 'الفتح',
    nameEnglish: 'Al-Fath',
    versesCount: 29,
    pageNumber: 511,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 49,
    nameArabic: 'الحجرات',
    nameEnglish: 'Al-Hujurat',
    versesCount: 18,
    pageNumber: 515,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 50,
    nameArabic: 'ق',
    nameEnglish: 'Qaf',
    versesCount: 45,
    pageNumber: 518,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 51,
    nameArabic: 'الذاريات',
    nameEnglish: 'Adh-Dhariyat',
    versesCount: 60,
    pageNumber: 520,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 52,
    nameArabic: 'الطور',
    nameEnglish: 'At-Tur',
    versesCount: 49,
    pageNumber: 523,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 53,
    nameArabic: 'النجم',
    nameEnglish: 'An-Najm',
    versesCount: 62,
    pageNumber: 526,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 54,
    nameArabic: 'القمر',
    nameEnglish: 'Al-Qamar',
    versesCount: 55,
    pageNumber: 528,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 55,
    nameArabic: 'الرحمن',
    nameEnglish: 'Ar-Rahman',
    versesCount: 78,
    pageNumber: 531,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 56,
    nameArabic: 'الواقعة',
    nameEnglish: 'Al-Waqi\'ah',
    versesCount: 96,
    pageNumber: 534,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 57,
    nameArabic: 'الحديد',
    nameEnglish: 'Al-Hadid',
    versesCount: 29,
    pageNumber: 537,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 58,
    nameArabic: 'المجادلة',
    nameEnglish: 'Al-Mujadila',
    versesCount: 22,
    pageNumber: 542,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 59,
    nameArabic: 'الحشر',
    nameEnglish: 'Al-Hashr',
    versesCount: 24,
    pageNumber: 545,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 60,
    nameArabic: 'الممتحنة',
    nameEnglish: 'Al-Mumtahanah',
    versesCount: 13,
    pageNumber: 549,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 61,
    nameArabic: 'الصف',
    nameEnglish: 'As-Saf',
    versesCount: 14,
    pageNumber: 551,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 62,
    nameArabic: 'الجمعة',
    nameEnglish: 'Al-Jumu\'ah',
    versesCount: 11,
    pageNumber: 553,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 63,
    nameArabic: 'المنافقون',
    nameEnglish: 'Al-Munafiqun',
    versesCount: 11,
    pageNumber: 554,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 64,
    nameArabic: 'التغابن',
    nameEnglish: 'At-Taghabun',
    versesCount: 18,
    pageNumber: 556,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 65,
    nameArabic: 'الطلاق',
    nameEnglish: 'At-Talaq',
    versesCount: 12,
    pageNumber: 558,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 66,
    nameArabic: 'التحريم',
    nameEnglish: 'At-Tahrim',
    versesCount: 12,
    pageNumber: 560,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 67,
    nameArabic: 'الملك',
    nameEnglish: 'Al-Mulk',
    versesCount: 30,
    pageNumber: 562,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 68,
    nameArabic: 'القلم',
    nameEnglish: 'Al-Qalam',
    versesCount: 52,
    pageNumber: 564,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 69,
    nameArabic: 'الحاقة',
    nameEnglish: 'Al-Haqqah',
    versesCount: 52,
    pageNumber: 566,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 70,
    nameArabic: 'المعارج',
    nameEnglish: 'Al-Ma\'arij',
    versesCount: 44,
    pageNumber: 568,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 71,
    nameArabic: 'نوح',
    nameEnglish: 'Nuh',
    versesCount: 28,
    pageNumber: 570,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 72,
    nameArabic: 'الجن',
    nameEnglish: 'Al-Jinn',
    versesCount: 28,
    pageNumber: 572,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 73,
    nameArabic: 'المزمل',
    nameEnglish: 'Al-Muzzammil',
    versesCount: 20,
    pageNumber: 574,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 74,
    nameArabic: 'المدثر',
    nameEnglish: 'Al-Muddaththir',
    versesCount: 56,
    pageNumber: 575,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 75,
    nameArabic: 'القيامة',
    nameEnglish: 'Al-Qiyamah',
    versesCount: 40,
    pageNumber: 577,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 76,
    nameArabic: 'الإنسان',
    nameEnglish: 'Al-Insan',
    versesCount: 31,
    pageNumber: 578,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 77,
    nameArabic: 'المرسلات',
    nameEnglish: 'Al-Mursalat',
    versesCount: 50,
    pageNumber: 580,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 78,
    nameArabic: 'النبأ',
    nameEnglish: 'An-Naba',
    versesCount: 40,
    pageNumber: 582,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 79,
    nameArabic: 'النازعات',
    nameEnglish: 'An-Nazi\'at',
    versesCount: 46,
    pageNumber: 583,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 80,
    nameArabic: 'عبس',
    nameEnglish: '\'Abasa',
    versesCount: 42,
    pageNumber: 585,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 81,
    nameArabic: 'التكوير',
    nameEnglish: 'At-Takwir',
    versesCount: 29,
    pageNumber: 586,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 82,
    nameArabic: 'الانفطار',
    nameEnglish: 'Al-Infitar',
    versesCount: 19,
    pageNumber: 587,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 83,
    nameArabic: 'المطففين',
    nameEnglish: 'Al-Mutaffifin',
    versesCount: 36,
    pageNumber: 587,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 84,
    nameArabic: 'الانشقاق',
    nameEnglish: 'Al-Inshiqaq',
    versesCount: 25,
    pageNumber: 589,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 85,
    nameArabic: 'البروج',
    nameEnglish: 'Al-Buruj',
    versesCount: 22,
    pageNumber: 590,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 86,
    nameArabic: 'الطارق',
    nameEnglish: 'At-Tariq',
    versesCount: 17,
    pageNumber: 591,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 87,
    nameArabic: 'الأعلى',
    nameEnglish: 'Al-A\'la',
    versesCount: 19,
    pageNumber: 591,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 88,
    nameArabic: 'الغاشية',
    nameEnglish: 'Al-Ghashiyah',
    versesCount: 26,
    pageNumber: 592,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 89,
    nameArabic: 'الفجر',
    nameEnglish: 'Al-Fajr',
    versesCount: 30,
    pageNumber: 593,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 90,
    nameArabic: 'البلد',
    nameEnglish: 'Al-Balad',
    versesCount: 20,
    pageNumber: 594,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 91,
    nameArabic: 'الشمس',
    nameEnglish: 'Ash-Shams',
    versesCount: 15,
    pageNumber: 595,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 92,
    nameArabic: 'الليل',
    nameEnglish: 'Al-Layl',
    versesCount: 21,
    pageNumber: 595,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 93,
    nameArabic: 'الضحى',
    nameEnglish: 'Ad-Duhaa',
    versesCount: 11,
    pageNumber: 596,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 94,
    nameArabic: 'الشرح',
    nameEnglish: 'Ash-Sharh',
    versesCount: 8,
    pageNumber: 596,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 95,
    nameArabic: 'التين',
    nameEnglish: 'At-Tin',
    versesCount: 8,
    pageNumber: 597,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 96,
    nameArabic: 'العلق',
    nameEnglish: 'Al-\'Alaq',
    versesCount: 19,
    pageNumber: 597,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 97,
    nameArabic: 'القدر',
    nameEnglish: 'Al-Qadr',
    versesCount: 5,
    pageNumber: 598,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 98,
    nameArabic: 'البينة',
    nameEnglish: 'Al-Bayyinah',
    versesCount: 8,
    pageNumber: 598,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 99,
    nameArabic: 'الزلزلة',
    nameEnglish: 'Az-Zalzalah',
    versesCount: 8,
    pageNumber: 599,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 100,
    nameArabic: 'العاديات',
    nameEnglish: 'Al-\'Adiyat',
    versesCount: 11,
    pageNumber: 599,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 101,
    nameArabic: 'القارعة',
    nameEnglish: 'Al-Qari\'ah',
    versesCount: 11,
    pageNumber: 600,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 102,
    nameArabic: 'التكاثر',
    nameEnglish: 'At-Takathur',
    versesCount: 8,
    pageNumber: 600,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 103,
    nameArabic: 'العصر',
    nameEnglish: 'Al-\'Asr',
    versesCount: 3,
    pageNumber: 601,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 104,
    nameArabic: 'الهمزة',
    nameEnglish: 'Al-Humazah',
    versesCount: 9,
    pageNumber: 601,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 105,
    nameArabic: 'الفيل',
    nameEnglish: 'Al-Fil',
    versesCount: 5,
    pageNumber: 601,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 106,
    nameArabic: 'قريش',
    nameEnglish: 'Quraysh',
    versesCount: 4,
    pageNumber: 602,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 107,
    nameArabic: 'الماعون',
    nameEnglish: 'Al-Ma\'un',
    versesCount: 7,
    pageNumber: 602,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 108,
    nameArabic: 'الكوثر',
    nameEnglish: 'Al-Kawthar',
    versesCount: 3,
    pageNumber: 602,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 109,
    nameArabic: 'الكافرون',
    nameEnglish: 'Al-Kafirun',
    versesCount: 6,
    pageNumber: 603,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 110,
    nameArabic: 'النصر',
    nameEnglish: 'An-Nasr',
    versesCount: 3,
    pageNumber: 603,
    revelationType: 'مدنية',
  ),
  SurahModel(
    id: 111,
    nameArabic: 'المسد',
    nameEnglish: 'Al-Masad',
    versesCount: 5,
    pageNumber: 603,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 112,
    nameArabic: 'الإخلاص',
    nameEnglish: 'Al-Ikhlas',
    versesCount: 4,
    pageNumber: 604,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 113,
    nameArabic: 'الفلق',
    nameEnglish: 'Al-Falaq',
    versesCount: 5,
    pageNumber: 604,
    revelationType: 'مكية',
  ),
  SurahModel(
    id: 114,
    nameArabic: 'الناس',
    nameEnglish: 'An-Nas',
    versesCount: 6,
    pageNumber: 604,
    revelationType: 'مكية',
  ),
];
